name: Checks

on:
  push:

jobs:
  test:
    runs-on: ubuntu
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Run tests
        run: npm test
